### ISSUE TITLE
Init Fails with: Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 60 seconds

### ISSUE THREAD

**Issue by mdfranz** [matanolabs/matano#35]
CLI Version (installed via docs today) 

```
mfranz@pixel-slate-cros:~/matano$  matano --version
matano/0.0.0 linux-x64 node-v14.18.1
mfranz@pixel-slate-cros:~/matano$ md5sum /usr/local/bin/matano
ca5dbebd474f92dd3448bc54398b93b2  /usr/local/bin/matano
```
Logs

```

 ›   MatanoDPMainStack |  99/104 | 10:27:12 AM | CREATE_COMPLETE      | AWS::Lambda::Function            | DPMainStack/Transformer/Function 
 ›   (TransformerFunctionFE009084) 
 ›   MatanoDPMainStack | 100/104 | 10:27:13 AM | CREATE_COMPLETE      | AWS::Lambda::Function            | DPMainStack/LakeWriter/Function (LakeWriterFunctionF773435F)
 › 
 ›   MatanoDPMainStack | 100/104 | 10:27:15 AM | CREATE_IN_PROGRESS   | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/LakeWriter/AlertsFunction/SqsEventSource:DPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805 
 ›   (LakeWriterAlertsFunctionSqsEventSourceDPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805B599AD6D) 
 ›   MatanoDPMainStack | 100/104 | 10:27:16 AM | CREATE_IN_PROGRESS   | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/Transformer/Function/SqsEventSource:DPMainStackDataBatcherOutputQueueD9616F88 
 ›   (TransformerFunctionSqsEventSourceDPMainStackDataBatcherOutputQueueD9616F888667E4CB) 
 ›   MatanoDPMainStack | 100/104 | 10:27:18 AM | CREATE_IN_PROGRESS   | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/LakeWriter/AlertsFunction/SqsEventSource:DPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805 
 ›   (LakeWriterAlertsFunctionSqsEventSourceDPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805B599AD6D) Resource creation Initiated
 ›   MatanoDPMainStack | 100/104 | 10:27:18 AM | CREATE_IN_PROGRESS   | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/LakeWriter/Function/SqsEventSource:DPMainStackMatanoLogstestlogsourceDefaultTableLakeWriterQueueC1E4E04B 
 ›   (LakeWriterFunctionSqsEventSourceDPMainStackMatanoLogstestlogsourceDefaultTableLakeWriterQueueC1E4E04BF71C3721) 
 ›   MatanoDPMainStack | 100/104 | 10:27:18 AM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/Transformer/Function/SqsEventSource:DPMainStackDataBatcherOutputQueueD9616F88 
 ›   (TransformerFunctionSqsEventSourceDPMainStackDataBatcherOutputQueueD9616F888667E4CB) Resource handler returned message: "Invalid request provided: Queue 
 ›   visibility timeout: 30 seconds is less than Function timeout: 60 seconds (Service: Lambda, Status Code: 400, Request ID: bc350930-2f6e-4f4c-9b68-809dd098f9c7)" 
 ›   (RequestToken: fb617621-26d6-2dd5-6739-1c4b5762885b, HandlerErrorCode: InvalidRequest)
 ›   MatanoDPMainStack | 100/104 | 10:27:19 AM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/LakeWriter/AlertsFunction/SqsEventSource:DPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805 
 ›   (LakeWriterAlertsFunctionSqsEventSourceDPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805B599AD6D) Resource creation cancelled
 ›   MatanoDPMainStack | 100/104 | 10:27:20 AM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/LakeWriter/Function/SqsEventSource:DPMainStackMatanoLogstestlogsourceDefaultTableLakeWriterQueueC1E4E04B 
 ›   (LakeWriterFunctionSqsEventSourceDPMainStackMatanoLogstestlogsourceDefaultTableLakeWriterQueueC1E4E04BF71C3721) Resource creation cancelled
 ›   MatanoDPMainStack | 100/104 | 10:27:22 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack       | MatanoDPMainStack The following resource(s) failed to 
 ›   create: [TransformerFunctionSqsEventSourceDPMainStackDataBatcherOutputQueueD9616F888667E4CB, 
 ›   LakeWriterFunctionSqsEventSourceDPMainStackMatanoLogstestlogsourceDefaultTableLakeWriterQueueC1E4E04BF71C3721, 
 ›   LakeWriterAlertsFunctionSqsEventSourceDPMainStackAlertsDefaultTableLakeWriterQueueC3CE4805B599AD6D]. Rollback requested by user.
```
Error Message

```
 ›   Failed resources:
 ›   MatanoDPMainStack | 10:27:18 AM | CREATE_FAILED        | AWS::Lambda::EventSourceMapping  | 
 ›   DPMainStack/Transformer/Function/SqsEventSource:DPMainStackDataBatcherOutputQueueD9616F88 
 ›   (TransformerFunctionSqsEventSourceDPMainStackDataBatcherOutputQueueD9616F888667E4CB) Resource handler returned message: "Invalid request provided: Queue 
 ›   visibility timeout: 30 seconds is less than Function timeout: 60 seconds (Service: Lambda, Status Code: 400, Request ID: bc350930-2f6e-4f4c-9b68-809dd098f9c7)" 
 ›   (RequestToken: fb617621-26d6-2dd5-6739-1c4b5762885b, HandlerErrorCode: InvalidRequest)
 ›   
 ›    ❌  DPMainStack (MatanoDPMainStack) failed: Error: The stack named MatanoDPMainStack failed creation, it may need to be manually deleted from the AWS console: 
 ›   ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 60 seconds 
 ›   (Service: Lambda, Status Code: 400, Request ID: bc350930-2f6e-4f4c-9b68-809dd098f9c7)" (RequestToken: fb617621-26d6-2dd5-6739-1c4b5762885b, HandlerErrorCode: 
 ›   InvalidRequest)
 ›       at FullCloudFormationDeployment.monitorDeployment (/snapshot/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
 ›       at processTicksAndRejections (internal/process/task_queues.js:95:5)
 ›       at deployStack2 (/snapshot/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
 ›       at /snapshot/node_modules/aws-cdk/lib/deploy.ts:39:11
 ›       at run (/snapshot/node_modules/p-queue/dist/index.js:163:29)
 ›   
 ›    ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named MatanoDPMainStack failed creation, it may need to be manually deleted from the AWS 
 ›   console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 60 
 ›   seconds (Service: Lambda, Status Code: 400, Request ID: bc350930-2f6e-4f4c-9b68-809dd098f9c7)" (RequestToken: fb617621-26d6-2dd5-6739-1c4b5762885b, 
 ›   HandlerErrorCode: InvalidRequest)
 ›       at deployStacks (/snapshot/node_modules/aws-cdk/lib/deploy.ts:61:11)
 ›       at processTicksAndRejections (internal/process/task_queues.js:95:5)
 ›       at CdkToolkit.deploy (/snapshot/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
 ›       at initCommandLine (/snapshot/node_modules/aws-cdk/lib/cli.ts:374:12)
 ›
 ›   Stack Deployments Failed: Error: The stack named MatanoDPMainStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: 
 ›   Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 60 seconds (Service: Lambda, 
 ›   Status Code: 400, Request ID: bc350930-2f6e-4f4c-9b68-809dd098f9c7)" (RequestToken: fb617621-26d6-2dd5-6739-1c4b5762885b, HandlerErrorCode: InvalidRequest)
 ›   Created temporary directory for configuration files: /tmp/mtnconfignGHkpS/config
```

**Comment by shaeqahmed** [comment]
Thanks for the catch! Looks like it broke with this change a few days ago: https://github.com/matanolabs/matano/commit/6e4d8ac1cd41f4ef7bd50534450ad8609a155fb3#diff-d3db90eeff29ff5c3897dcc475cd4508d6cac54c9d393d4e9f35856c94f7d16c. Im verifying the problem locally + deploying the fix right now.

**Note:** This likely only effects new stacks, since after creation, the event source mapping already exists and isnt updated causing this bug

**Comment by mdfranz** [comment]
This works

```mfranz@x360-cros-debian:~$ mfranz@x360-cros-debian:~$ matano init
━━━ Matano: Get started Wizard ━━━

Welcome to the Matano init wizard. This will get you started with Matano.
Follow the prompts to get started. You can always change these values later.

✔ Which AWS Region to deploy to? · us-east-1
✔ What is the AWS Account ID to deploy to? · 647303185053
✔ Do you have an existing matano directory? (y/N) · false
  I will generate a Matano directory in the current directory.
✔ What is the name of the directory to generate?(use . for current directory) · e1
✔ Generated Matano directory at /home/mfranz/e1.
✔ Successfully initialized your account.
✔ Successfully deployed Matano.

· Here are some useful values to get you started:

  ┌───────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────┐
  │             Name              │                                   Value                                   │                 Description
